import { readFileSync } from "node:fs";
import { join } from "node:path";

import {
  ENGINE_LIMITS,
  EXIT_CODE_MEANINGS,
  FLAG_EDITORIAL,
  FLAG_GROUP_META,
} from "./cli-editorial";

/**
 * The flag reference, read from what the CLI actually ships.
 *
 * This file used to be a hand-written copy of the `HELP` string in
 * `packages/cli/src/cli-args.ts` — thirty flags, the exit codes and the engine
 * limits, with a header promising the descriptions were that string reflowed.
 * The documentation audit of 2026-08-13 found four drifts in it: `--coverage`
 * missing entirely, `--max-pages` described as a ceiling when under structural
 * coverage it is a floor, `--depth 0` described as "the entry page alone" when
 * sitemap URLs are seeded regardless, and an engine limit of 500 the CLI never
 * reaches. The only guard rail was a CLI test listing twelve flag names by
 * hand, and it caught none of them.
 *
 * So the data now comes from `packages/cli/flags.json`, generated from the flag
 * table by `pnpm --filter @goflag/cli generate:flags`, regenerated by the
 * pre-commit hook when that table is staged, and compared against the table by
 * `catalog.test.ts` — which is the guarantee, since a hook can be skipped.
 *
 * **Read, not imported.** Invariant I3 forbids `apps/**` from importing
 * `packages/cli`: the site must not depend on that package's build, and the
 * table carries `apply` closures that are neither serialisable nor anything a
 * marketing site should bundle. Same mechanism as `rules-catalog.ts` and
 * `changelog.ts`.
 *
 * What the file cannot carry — group headings and the longer description a page
 * has room for — lives in `cli-editorial.ts`, and `cli-reference.test.ts` fails
 * when the two sets of flag names stop matching.
 */

interface GeneratedFlag {
  name: string;
  short: string | null;
  arg: string | null;
  default: string | null;
  requires: string | null;
  group: string;
  description: string;
}

interface GeneratedFlagCatalog {
  flags: GeneratedFlag[];
  exitCodes: Array<{ code: number; label: string }>;
}

export interface Flag {
  /** Long form, with its argument placeholder if it takes one. */
  flag: string;
  /** Short form, when the CLI accepts one. */
  short?: string;
  /** Printed default, or `undefined` when the flag is a plain switch. */
  default?: string;
  description: string;
  /** Set when the flag is only valid alongside another. */
  requires?: string;
}

export interface FlagGroup {
  id: string;
  title: string;
  /** Why this group exists, in one line. */
  intro: string;
  flags: readonly Flag[];
}

const CATALOG: GeneratedFlagCatalog = JSON.parse(
  readFileSync(join(process.cwd(), "..", "..", "packages", "cli", "flags.json"), "utf8"),
);

function toFlag(flag: GeneratedFlag): Flag {
  const description = FLAG_EDITORIAL[flag.name];
  if (!description) {
    // Loud rather than partial: a flag rendered with the terminal's clipped
    // wording, or with none, looks like one nobody thought worth explaining.
    throw new Error(
      `cli-editorial.ts has no entry for \`${flag.name}\`. Add one, or the ` +
        `reference page ships a flag with no explanation.`,
    );
  }
  return {
    flag: flag.arg ? `${flag.name} ${flag.arg}` : flag.name,
    ...(flag.short ? { short: flag.short } : {}),
    ...(flag.default ? { default: flag.default } : {}),
    ...(flag.requires ? { requires: flag.requires } : {}),
    description,
  };
}

/**
 * Groups in the order the page reads best, each holding the flags the CLI
 * assigned to it. A flag whose group is not in `FLAG_GROUP_META` would vanish
 * from the page, so the test asserts every group id is claimed.
 */
export const FLAG_GROUPS: readonly FlagGroup[] = FLAG_GROUP_META.map((meta) => ({
  ...meta,
  flags: CATALOG.flags.filter((f) => f.group === meta.id).map(toFlag),
}));

export const EXIT_CODES: ReadonlyArray<{
  code: number;
  label: string;
  meaning: string;
  tone: "green" | "yellow" | "red";
}> = CATALOG.exitCodes.map((exit) => {
  const editorial = EXIT_CODE_MEANINGS[exit.code];
  if (!editorial) throw new Error(`cli-editorial.ts has no meaning for exit code ${exit.code}.`);
  return { ...exit, ...editorial };
});

export { ENGINE_LIMITS };
