import { readFileSync } from "node:fs";
import { join } from "node:path";

import { RECIPROCITY_CODES, RULE_EDITORIAL } from "./rules-editorial";

/**
 * The rule catalogue, read from what the engine actually ships.
 *
 * This file used to be a hand-written copy of `packages/cli/src/lib/rules/`,
 * 544 lines of it, with a header promising the fields were verbatim. They were
 * not: the documentation audit of 2026-08-13 found a rule message wrong since
 * 0.2.2 (`Conflicting indexing directives`, where the engine prints `robots`)
 * and a fourth reciprocity code documented that no branch could emit. A copy
 * kept by hand is a copy that drifts, and the drift is invisible precisely
 * because both sides look authoritative.
 *
 * So the data now comes from `packages/cli/rules.json`, generated from the
 * registry by `pnpm --filter @goflag/cli generate:catalog`, regenerated by the
 * pre-commit hook when a rule file is staged, and compared against the registry
 * by `catalog.test.ts` — which is the guarantee, since a hook can be skipped.
 *
 * **Read, not imported.** Invariant I3 forbids `apps/**` from importing
 * `packages/cli`: the site must not depend on either package's build, and the
 * registry carries `evaluate` closures that are neither serialisable nor
 * anything a marketing site should bundle. The same reasoning, and the same
 * mechanism, as `changelog.ts` reading each package's `CHANGELOG.md`.
 *
 * What the file cannot carry — the cost of a mistake, and a sample message —
 * lives in `rules-editorial.ts`, and `rules-catalog.test.ts` fails when the two
 * sets of ids stop matching.
 */

export type RuleSeverity = "error" | "warning" | "info";

export type RuleRigor =
  "spec-required" | "spec-recommended" | "vendor-spec" | "guideline" | "heuristic";

/** How authoritative a cited document is, on the source catalogue's own scale. */
export type SourceRigor = "normative" | "vendor-spec" | "guideline" | "heuristic";

export interface SourceDoc {
  id: string;
  publisher: string;
  title: string;
  rigor: SourceRigor;
  /** Deep link, with the section anchor already applied. */
  url: string;
}

export interface RuleFix {
  title: string;
  snippet: string;
  language: "tsx" | "ts";
}

export interface RuleDoc {
  id: string;
  scope: "page" | "site" | "prose";
  /**
   * `null` on prose rules. They produce no verdict, so there is nothing for a
   * severity to describe — inventing one would make a question look like a
   * finding, which is the single thing this design refuses to do.
   */
  severity: RuleSeverity | null;
  /** The rule's own one-line statement of the policy. */
  summary: string;
  /**
   * An example of the message the CLI prints, with values filled in. On a prose
   * rule this is the question printed under "Needs judgment". Editorial: the
   * real message is built at audit time from what the page said.
   */
  message: string;
  /** Editorial: what the mistake costs. Not present in the registry. */
  why: string;
  fix?: RuleFix;
  /**
   * `null` on the cross-page rules only: they still run on the pre-catalogue
   * contract and pick up rigor when they move onto the descriptor (phase G).
   * The generated catalogue emits the gap rather than hiding it.
   */
  rigor: RuleRigor | null;
  /** Ids into `SOURCES`. Empty only where `rigor` is null, for the same reason. */
  sources: readonly string[];
}

interface GeneratedCatalog {
  counts: { page: number; site: number; prose: number };
  sources: Record<string, SourceDoc>;
  rules: Array<{
    id: string;
    scope: "page" | "site" | "prose";
    severity: RuleSeverity | null;
    summary: string;
    rigor: RuleRigor | null;
    sources: string[];
    prose?: string;
    fix?: { title: string; snippet: string; language: string };
  }>;
}

/**
 * Read at module load, which on this site is build time — every consumer is a
 * server component, a route handler or an OG image.
 *
 * The path is relative to `process.cwd()`, which Next sets to the app
 * directory, exactly as `changelog.ts` resolves the changelogs.
 */
const CATALOG: GeneratedCatalog = JSON.parse(
  readFileSync(join(process.cwd(), "..", "..", "packages", "cli", "rules.json"), "utf8"),
);

function toDoc(rule: GeneratedCatalog["rules"][number]): RuleDoc {
  const editorial = RULE_EDITORIAL[rule.id];
  if (!editorial) {
    // Loud rather than partial: a rule rendered without its prose looks like a
    // rule nobody thought worth explaining.
    throw new Error(
      `rules-editorial.ts has no entry for \`${rule.id}\`. Add one, or the ` +
        `catalogue page ships a rule with no explanation.`,
    );
  }

  // A prose rule's message *is* its question, and the engine carries that, so
  // no sample is written beside it. Everything else needs one.
  const message = rule.prose ?? editorial.message;
  if (!message) {
    throw new Error(
      `rules-editorial.ts has no message for \`${rule.id}\`. Add one, or the ` +
        `catalogue page shows a rule without an example of what it prints.`,
    );
  }

  return {
    id: rule.id,
    scope: rule.scope,
    severity: rule.severity,
    summary: rule.summary,
    message,
    why: editorial.why,
    ...(rule.fix
      ? {
          fix: {
            title: rule.fix.title,
            snippet: rule.fix.snippet,
            language: rule.fix.language === "tsx" ? "tsx" : "ts",
          },
        }
      : {}),
    rigor: rule.rigor,
    sources: rule.sources,
  };
}

/** The documents the shipped rules cite. Only the cited ones are exported. */
export const SOURCES: Readonly<Record<string, SourceDoc>> = CATALOG.sources;

export const ALL_RULES: readonly RuleDoc[] = CATALOG.rules.map(toDoc);

export const PAGE_RULES: readonly RuleDoc[] = ALL_RULES.filter((r) => r.scope === "page");
export const SITE_RULES: readonly RuleDoc[] = ALL_RULES.filter((r) => r.scope === "site");
export const PROSE_RULES: readonly RuleDoc[] = ALL_RULES.filter((r) => r.scope === "prose");

export { RECIPROCITY_CODES };

export const SEVERITY_ORDER: Record<RuleSeverity, number> = {
  error: 0,
  warning: 1,
  info: 2,
};
