import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

import { FULL_REPORT, GATE_REPORT, SAMPLES, SUMMARY_REPORT, type Span } from "./transcripts";

/**
 * The transcripts are generated by `packages/cli` and compared to the renderers
 * byte for byte over there. These check the seam: that the tokeniser turns
 * those bytes into the spans the panel paints without inventing or losing any.
 */

const dir = join(process.cwd(), "..", "..", "packages", "cli", "test", "fixtures", "transcripts");

/** Built, not written literally — see the note in `transcripts.ts`. */
const ANY_ESCAPE = new RegExp(`${"\u001b"}\\[`);

/** The plain-text half of the same render, trimmed the way the reader trims. */
function plainLines(id: string): string[] {
  const lines = readFileSync(join(dir, `${id}.txt`), "utf8").split("\n");
  while (lines.length && lines[0]!.trim() === "") lines.shift();
  while (lines.length && lines[lines.length - 1]!.trim() === "") lines.pop();
  return lines;
}

const text = (span: Span) => (typeof span === "string" ? span : span.t);
const flatten = (spans: readonly Span[]) => spans.map(text).join("");

describe("the transcripts the panel paints", () => {
  it("carries every generated view, in the order the generator wrote them", () => {
    // Against the manifest rather than a list spelled out here: a fourth
    // transcript is a normal thing to add, and a test that has to be edited
    // for it teaches people to edit tests.
    const manifest = JSON.parse(readFileSync(join(dir, "index.json"), "utf8")) as Array<{
      id: string;
    }>;
    expect(SAMPLES.map((s) => s.id)).toEqual(manifest.map((entry) => entry.id));
    expect(SAMPLES.length).toBeGreaterThanOrEqual(3);
    expect(FULL_REPORT.command).toContain("npx @goflag/cli");
    expect(GATE_REPORT.command).toContain("--regressions-only");
  });

  it.each(["full", "summary", "gate"])("loses no character of the output: %s", (id) => {
    // The strongest thing this file can say. `<id>.ansi` and `<id>.txt` are one
    // render with one argument flipped, so stripping the colour from the spans
    // has to give the plain text back exactly. A tokeniser that swallowed an
    // escape, or a character next to one, fails here.
    const sample = SAMPLES.find((s) => s.id === id)!;
    expect(sample.lines.map(flatten)).toEqual(plainLines(id));
  });

  it("paints the counts line bold *and* yellow", () => {
    // `render-terminal.ts` wraps the colour in the bold: `c(bold, c(yellow, …))`.
    // A span with one slot for both rendered it as one or the other, which is
    // why `bold` is an attribute here rather than a sixth tone.
    const counts = FULL_REPORT.lines.find((line) =>
      flatten(line).includes("1 broken link   2 missing translations"),
    );
    expect(counts).toBeDefined();
    expect(counts!.filter((s) => typeof s !== "string")).toContainEqual(
      expect.objectContaining({ tone: "yellow", bold: true }),
    );
  });

  it("shows the rigor tag the hand-written copy never grew", () => {
    // The regression that ended the previous file. `[rigor]` is printed by
    // `renderSummaryTerminal` alone, it shipped on 2026-08-15, and the
    // transcription on this site still read `warn og.image.missing ×9` — with
    // no tag — under a caption that said "Real output".
    const summary = SUMMARY_REPORT.lines.map(flatten).join("\n");
    expect(summary).toContain("og.image.missing [guideline]");
    expect(summary).toContain("robots.conflict [vendor-spec]");
  });

  it("keeps the blank lines that separate sections, and drops the ones at the edges", () => {
    expect(FULL_REPORT.lines[0]!.length).toBeGreaterThan(0);
    expect(FULL_REPORT.lines.at(-1)!.length).toBeGreaterThan(0);
    expect(FULL_REPORT.lines.some((line) => line.length === 0)).toBe(true);
  });

  it("leaves no escape sequence in the text it hands the panel", () => {
    for (const sample of SAMPLES) {
      expect(sample.lines.map(flatten).join("\n")).not.toMatch(ANY_ESCAPE);
    }
  });
});
