/**
 * Generates `src/locale/generated.ts` by asking ICU what it knows.
 *
 * TypeScript cannot query ICU at compile time, so the literal unions have to
 * exist as source. Enumerating them by hand would be a table that drifts from
 * the runtime that validates against it — so they are enumerated *from* that
 * runtime instead, and regenerating is how they stay true.
 *
 *   pnpm --filter @goflag/next generate:locales
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

import { EXCLUDED_LANGUAGES, EXCLUDED_REGIONS } from "../src/locale/excluded";

const languageNames = new Intl.DisplayNames(["en"], { type: "language", fallback: "none" });
const regionNames = new Intl.DisplayNames(["en"], { type: "region", fallback: "none" });

const LETTERS = "abcdefghijklmnopqrstuvwxyz".split("");

const languages: string[] = [];
const regions: string[] = [];

for (const a of LETTERS) {
  for (const b of LETTERS) {
    const two = a + b;
    if (languageNames.of(two) && !EXCLUDED_LANGUAGES.has(two)) languages.push(two);

    const upper = two.toUpperCase();
    if (regionNames.of(upper) && !EXCLUDED_REGIONS.has(upper)) regions.push(upper);
  }
}

// UN M.49 numeric regions. Google documents `es-419`, and CLDR carries the
// rest of the groupings, so they are enumerated the same way rather than
// guessed at.
for (let n = 0; n < 1000; n += 1) {
  const code = String(n).padStart(3, "0");
  if (regionNames.of(code)) regions.push(code);
}

const union = (values: string[]) => values.map((v) => `  | "${v}"`).join("\n");

writeFileSync(
  join(import.meta.dirname, "../src/locale/generated.ts"),
  `// Generated by scripts/generate-locale-types.ts — do not edit.
//
// Enumerated from the ICU data shipped with Node, so these unions cannot drift
// from the runtime that validates against them. Regenerate with
// \`pnpm --filter @goflag/next generate:locales\` after a Node major.
//
// ${languages.length} languages, ${regions.length} regions.

/** A language subtag ICU recognises. */
export type Language =
${union(languages)};

/** A region subtag ICU recognises: ISO 3166-1 alpha-2, plus UN M.49 numerics. */
export type Region =
${union(regions)};
`,
);

console.log(`generated ${languages.length} languages, ${regions.length} regions`);
