#!/usr/bin/env tsx
/**
 * Write `rules.json` from the rule registry.
 *
 * The file is committed, and `catalog.test.ts` fails when it no longer matches
 * the registry — so a rule added without regenerating is a red test, not a
 * documentation site that quietly says something false for four versions.
 *
 * Run by the pre-commit hook when a rule file is staged, and by hand with
 * `pnpm --filter @goflag/cli generate:catalog`.
 *
 * Same shape as `packages/next/src/locale/generated.ts`: a generated artefact
 * lives next to the source it derives from, carries a "do not edit" marker, and
 * is regenerated by a named script rather than by whoever remembers.
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { buildRuleCatalog, serialiseCatalog } from "../src/lib/rules/catalog";

const here = dirname(fileURLToPath(import.meta.url));
const target = join(here, "..", "rules.json");

// No version stamp: the file would then change on every release, going stale
// during `pnpm release` itself and reddening the release commit. `goflag rules
// --json` adds the version at print time, where the caller actually asked.
writeFileSync(target, serialiseCatalog(buildRuleCatalog()), "utf8");

const { counts } = buildRuleCatalog();
process.stdout.write(
  `rules.json: ${counts.page} page, ${counts.site} site, ${counts.prose} prose\n`,
);
