#!/usr/bin/env tsx
/**
 * Write `flags.json` from the flag table.
 *
 * The file is committed, and `catalog.test.ts` fails when it no longer matches
 * the table — so a flag added without regenerating is a red test, not a
 * reference page that quietly omits `--coverage` for four versions, which is
 * what the documentation audit actually found.
 *
 * Run by the pre-commit hook when the flag table is staged, and by hand with
 * `pnpm --filter @goflag/cli generate:flags`.
 *
 * Same shape as `generate-catalog.ts`, deliberately: a generated artefact lives
 * next to the source it derives from and is regenerated by a named script
 * rather than by whoever remembers.
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { buildFlagCatalog, serialiseFlags } from "../src/lib/flags/catalog";

const here = dirname(fileURLToPath(import.meta.url));

// No version stamp, for the same reason `rules.json` carries none: the file
// would change on every release and go stale during `pnpm release` itself.
// `goflag flags` adds the version at print time, where the caller asked.
writeFileSync(join(here, "..", "flags.json"), serialiseFlags(buildFlagCatalog()), "utf8");

const { counts } = buildFlagCatalog();
process.stdout.write(
  `flags.json: ${counts.flags} flags, ${counts.withShortForm} with a short form, ` +
    `${counts.takingValue} taking a value\n`,
);
